###
POST http://localhost:9000/api/users HTTP/1.1
Content-type: application/json

{ 
    "name": "Georgi",
    "contacts": 17,
    "age": 22
 }

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/ HTTP/1.1

###
PUT http://localhost:9000/api/users/ HTTP/1.1
Content-type: application/json

{ 
    "name": "George",
    "contacts": 17,
    "age": 22
 }

###

DELETE http://localhost:9000/api/users/ HTTP/1.1